steps:
  # Create Artifact Registry repository if it doesn't exist
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'artifacts'
      - 'repositories'
      - 'create'
      - 'adk-audio-assistant'
      - '--repository-format=docker'
      - '--location=us-central1'
      - '--description=Repository for ADK Audio Assistant'
      - '--quiet'
    id: 'create-repo'
    allowFailure: true  # Allow failure if repo already exists

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/adk-audio-assistant/audio-assistant:$SHORT_SHA', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/adk-audio-assistant/audio-assistant:$SHORT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'adk-audio-assistant'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/adk-audio-assistant/audio-assistant:$SHORT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--min-instances=1'
      - '--max-instances=10'
      - '--session-affinity'
      - '--set-env-vars=GOOGLE_GENAI_USE_VERTEXAI=TRUE,GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GOOGLE_CLOUD_LOCATION=us-central1,BIGQUERY_DATASET=$_BIGQUERY_DATASET,VERTEX_AI_SEARCH_DATASTORE_ID=$_VERTEX_AI_SEARCH_DATASTORE_ID,ADK_MODEL=$_ADK_MODEL'
      - '--update-secrets=ALPHA_VANTAGE_API_KEY=ALPHA_VANTAGE_API_KEY:latest'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/adk-audio-assistant/audio-assistant:$SHORT_SHA'

substitutions:
  _BIGQUERY_DATASET: 'fsi-banking-agentspace.awm'
  _VERTEX_AI_SEARCH_DATASTORE_ID: 'citi_perspectives_datastore'
  _ADK_MODEL: 'gemini-2.0-flash-live-preview-04-09'
